### ISSUE TITLE
MimeType: use library instead of finfo?

### ISSUE THREAD

**Issue by Gounlaf** [riotkit-org/file-repository#21]
Hi,

I'm wondering if we should use https://github.com/hoaproject/Mime for detecting file mime types.
Why? It allows file-repository "owner" to specify their own mime-types list (basically [the one from Apache](https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types)); the shared one on server might be not up to date.

I don't really know if the "cost" (implementation + performances) worth it.

**Comment by blackandred** [comment]
Hello,

Currently I don't know if its worth to overimplement this. Maybe we could wait for a first issue that would bring a problem with mime types?

**Comment by Gounlaf** [comment]
That's ok for me!
We can close (and maybe put a reminder in wiki?)

**Comment by blackandred** [comment]
I suggest to create a markdown formatted file in the "docs" directory about how we support mime types and what could be suggested in the future in case it might be not enough. What do you think?

**Comment by Gounlaf** [comment]
Let's go :)

**Comment by blackandred** [comment]
I do not know if this is still valid in the second version?
