### ISSUE TITLE
MimeType: might fix upload through "collection" routes

### ISSUE THREAD

**Issue by Gounlaf** [riotkit-org/file-repository#24]
Hi @blackandred,

If you can take a look here and let me know what you think: https://github.com/Gounlaf/file-repository/commit/ed101606b34c073f6b2885dd24dc79d056c024c8

Thanks

**Comment by blackandred** [comment]
The project was reborn and will be the actively maintained. Please take a look at the version v2 that is currently on master and soon will be released as stable.
